name: flake8 Lint

on: [push]

jobs:
    run-linters:
      name: Run Flake8
      runs-on: ubuntu-latest
  
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.11
  
        - name: Install Python dependencies
          run: pip install flake8
  
        - name: Run linters
          uses: wearerequired/lint-action@v2
          with:
            flake8: true